package user.jacobandrudy.projects;
import java.util.HashMap;
public class RPS {
    public static void main(String args[]){
        HashMap<Character, Integer> points = new HashMap<Character, Integer>();
        HashMap<String, Integer> result = new HashMap<String, Integer>();
        HashMap<String, Character> counterPick = new HashMap<String, Character>();
        HashMap<Character, Integer> solution = new HashMap<Character, Integer>();
        points.put('X', 1);
        points.put('Y', 2);
        points.put('Z', 3);
        result.put("AX", 3);
        result.put("BX", 0);
        result.put("CX", 6);
        result.put("AY", 6);
        result.put("BY", 3);
        result.put("CY", 0);
        result.put("AZ", 0);
        result.put("BZ", 6);
        result.put("CZ", 3);
        solution.put('X', 0);
        solution.put('Y', 3);
        solution.put('Z', 6);
        

        counterPick.put("AX", 'Y');
        counterPick.put("BX", 'Z');
        counterPick.put("CX", 'X');
        counterPick.put("AY", 'X');
        counterPick.put("BY", 'Y');
        counterPick.put("CY", 'Z');
        counterPick.put("AZ", 'Y');
        counterPick.put("BZ", 'Z');
        counterPick.put("CZ", 'X');
        Character[][] inputArray = createInput(input());
        int sol = 0;
        for (int i = 0; i < inputArray.length; i++) {
            String matchup = "";
            matchup += inputArray[i][0];
            matchup += inputArray[i][1];

            sol += points.get(counterPick.get(matchup)) + solution.get(inputArray[i][1]);
        }
        System.out.println(sol);
    }

    public static Character[][] createInput(String input) {
        System.out.println(input.length()/2);
        Character[][] inputArray = new Character[input.length()/2][2];
        int counter = 0;
        for (int row = 0; row < inputArray.length; row++) {
            for (int col = 0; col < inputArray[0].length; col++) {
                inputArray[row][col] = input.charAt(counter);
                counter++;
            }
        }
        return inputArray;
    }

    public static String input() {
        return "AZ" +
                "AY" +
                "BX" +
                "BX" +
                "CX" +
                "BX" +
                "AX" +
                "AX" +
                "CX" +
                "AX" +
                "AX" +
                "AY" +
                "BX" +
                "AY" +
                "CX" +
                "CX" +
                "AX" +
                "AY" +
                "CX" +
                "BX" +
                "AX" +
                "BX" +
                "AX" +
                "AX" +
                "BY" +
                "BY" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "AY" +
                "AX" +
                "BX" +
                "BY" +
                "AY" +
                "CZ" +
                "CX" +
                "AX" +
                "AY" +
                "AX" +
                "AX" +
                "AY" +
                "AX" +
                "AY" +
                "AX" +
                "BX" +
                "CX" +
                "AX" +
                "BX" +
                "AX" +
                "CX" +
                "AY" +
                "BX" +
                "BX" +
                "AX" +
                "AX" +
                "CY" +
                "BX" +
                "AX" +
                "CX" +
                "BX" +
                "BX" +
                "AX" +
                "AX" +
                "BX" +
                "AY" +
                "CX" +
                "AY" +
                "AX" +
                "AX" +
                "AY" +
                "BX" +
                "AX" +
                "AX" +
                "AX" +
                "BY" +
                "AX" +
                "AX" +
                "AY" +
                "AX" +
                "AX" +
                "BY" +
                "BY" +
                "BX" +
                "CX" +
                "BY" +
                "AX" +
                "CX" +
                "CX" +
                "AY" +
                "AX" +
                "AZ" +
                "BX" +
                "CX" +
                "AY" +
                "BX" +
                "AX" +
                "AX" +
                "AX" +
                "AY" +
                "CX" +
                "AX" +
                "AZ" +
                "AX" +
                "AY" +
                "BY" +
                "AX" +
                "CX" +
                "BX" +
                "AY" +
                "BZ" +
                "BX" +
                "CY" +
                "BX" +
                "BZ" +
                "AY" +
                "BX" +
                "CX" +
                "CY" +
                "AX" +
                "AY" +
                "AX" +
                "BX" +
                "AY" +
                "BY" +
                "AX" +
                "CY" +
                "AY" +
                "BY" +
                "AX" +
                "BY" +
                "BX" +
                "BY" +
                "AX" +
                "BY" +
                "AX" +
                "CZ" +
                "AX" +
                "CX" +
                "AY" +
                "AX" +
                "CX" +
                "AX" +
                "AX" +
                "AX" +
                "CX" +
                "BZ" +
                "AX" +
                "BY" +
                "BX" +
                "AY" +
                "AX" +
                "AX" +
                "BY" +
                "BY" +
                "AY" +
                "BX" +
                "AX" +
                "CY" +
                "AX" +
                "CX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "CZ" +
                "CX" +
                "AZ" +
                "CZ" +
                "AX" +
                "AY" +
                "BX" +
                "CX" +
                "BX" +
                "BY" +
                "CX" +
                "BX" +
                "AX" +
                "AX" +
                "AX" +
                "AY" +
                "BX" +
                "BY" +
                "AX" +
                "CX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "CY" +
                "AZ" +
                "CX" +
                "AX" +
                "AY" +
                "BX" +
                "AY" +
                "AX" +
                "AY" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "AY" +
                "AX" +
                "BX" +
                "AX" +
                "AX" +
                "CY" +
                "CY" +
                "AX" +
                "CX" +
                "AX" +
                "AX" +
                "CX" +
                "CX" +
                "BZ" +
                "BX" +
                "BX" +
                "AX" +
                "AY" +
                "BY" +
                "AX" +
                "AX" +
                "CX" +
                "CX" +
                "CX" +
                "BX" +
                "CX" +
                "BY" +
                "AX" +
                "BY" +
                "BX" +
                "BX" +
                "AX" +
                "BY" +
                "AY" +
                "CX" +
                "BX" +
                "CX" +
                "AY" +
                "BX" +
                "CX" +
                "AX" +
                "CX" +
                "AX" +
                "BY" +
                "AX" +
                "AX" +
                "BZ" +
                "CX" +
                "BX" +
                "CX" +
                "BX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "CX" +
                "CX" +
                "AX" +
                "AZ" +
                "AY" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "CY" +
                "CY" +
                "BZ" +
                "AX" +
                "AX" +
                "BX" +
                "BX" +
                "AY" +
                "AX" +
                "BY" +
                "AX" +
                "BY" +
                "AX" +
                "CY" +
                "CX" +
                "AY" +
                "BY" +
                "CX" +
                "AX" +
                "AX" +
                "AX" +
                "AY" +
                "AX" +
                "AX" +
                "AX" +
                "BY" +
                "BX" +
                "CX" +
                "CY" +
                "AY" +
                "AZ" +
                "BX" +
                "CX" +
                "BX" +
                "CX" +
                "AX" +
                "BZ" +
                "BY" +
                "AX" +
                "CX" +
                "AY" +
                "BX" +
                "BX" +
                "AY" +
                "AX" +
                "AX" +
                "AY" +
                "AX" +
                "BX" +
                "AX" +
                "AX" +
                "CY" +
                "CY" +
                "AY" +
                "AY" +
                "BY" +
                "BY" +
                "BY" +
                "BX" +
                "AX" +
                "AY" +
                "BY" +
                "BX" +
                "AY" +
                "AX" +
                "AY" +
                "CX" +
                "CX" +
                "BY" +
                "AY" +
                "BY" +
                "AY" +
                "AX" +
                "BY" +
                "BX" +
                "CX" +
                "AX" +
                "AX" +
                "AX" +
                "BY" +
                "BX" +
                "AX" +
                "BY" +
                "AY" +
                "AX" +
                "CX" +
                "AX" +
                "BY" +
                "AX" +
                "AX" +
                "BY" +
                "AY" +
                "AX" +
                "CY" +
                "BZ" +
                "AY" +
                "CX" +
                "AY" +
                "AX" +
                "BY" +
                "AX" +
                "BY" +
                "BY" +
                "BX" +
                "BX" +
                "AX" +
                "AX" +
                "CX" +
                "BY" +
                "BX" +
                "CX" +
                "BY" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "BY" +
                "CX" +
                "BX" +
                "AX" +
                "AX" +
                "AY" +
                "CY" +
                "AY" +
                "BX" +
                "AX" +
                "BX" +
                "AX" +
                "AY" +
                "BY" +
                "AX" +
                "CX" +
                "CX" +
                "AY" +
                "BX" +
                "CY" +
                "AY" +
                "BX" +
                "AX" +
                "AY" +
                "CX" +
                "AX" +
                "AX" +
                "BY" +
                "AY" +
                "BX" +
                "BY" +
                "BY" +
                "AX" +
                "AX" +
                "AX" +
                "BY" +
                "AY" +
                "AX" +
                "BX" +
                "AY" +
                "AY" +
                "BX" +
                "CY" +
                "AX" +
                "AY" +
                "AX" +
                "BX" +
                "AX" +
                "BX" +
                "CZ" +
                "AX" +
                "AX" +
                "BY" +
                "AX" +
                "AX" +
                "AX" +
                "CZ" +
                "CX" +
                "AZ" +
                "CY" +
                "BX" +
                "AY" +
                "BX" +
                "AX" +
                "AY" +
                "AX" +
                "CX" +
                "AX" +
                "AX" +
                "CY" +
                "AZ" +
                "CY" +
                "BY" +
                "BX" +
                "BX" +
                "AY" +
                "CX" +
                "BX" +
                "AZ" +
                "AX" +
                "AZ" +
                "CX" +
                "AX" +
                "CZ" +
                "CX" +
                "BZ" +
                "CY" +
                "BY" +
                "AX" +
                "BY" +
                "AX" +
                "AX" +
                "CX" +
                "BX" +
                "AX" +
                "CZ" +
                "BY" +
                "BY" +
                "AY" +
                "BY" +
                "AX" +
                "AX" +
                "BY" +
                "AX" +
                "AX" +
                "CY" +
                "CX" +
                "AX" +
                "CY" +
                "CX" +
                "BX" +
                "BX" +
                "AX" +
                "BY" +
                "AY" +
                "AX" +
                "BY" +
                "BY" +
                "BX" +
                "BX" +
                "AX" +
                "BX" +
                "BX" +
                "BY" +
                "BY" +
                "CX" +
                "BX" +
                "BX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "AY" +
                "CY" +
                "AX" +
                "AY" +
                "CZ" +
                "AY" +
                "CX" +
                "AX" +
                "CY" +
                "AX" +
                "AX" +
                "AY" +
                "AZ" +
                "AY" +
                "AY" +
                "AX" +
                "AY" +
                "AZ" +
                "CX" +
                "CZ" +
                "BX" +
                "AX" +
                "AX" +
                "BX" +
                "AX" +
                "AX" +
                "AX" +
                "CX" +
                "AX" +
                "AY" +
                "AX" +
                "AX" +
                "AY" +
                "CZ" +
                "CX" +
                "AX" +
                "AX" +
                "AZ" +
                "AX" +
                "CX" +
                "AY" +
                "CX" +
                "AY" +
                "CX" +
                "CX" +
                "AX" +
                "AX" +
                "AY" +
                "BY" +
                "CX" +
                "CX" +
                "BX" +
                "BZ" +
                "BX" +
                "BX" +
                "AX" +
                "CX" +
                "AY" +
                "CX" +
                "AZ" +
                "BX" +
                "BY" +
                "AY" +
                "AY" +
                "AX" +
                "AY" +
                "AX" +
                "AX" +
                "AY" +
                "AX" +
                "AX" +
                "BZ" +
                "AX" +
                "AX" +
                "AX" +
                "BY" +
                "BY" +
                "CZ" +
                "AY" +
                "AY" +
                "BY" +
                "AX" +
                "BX" +
                "CX" +
                "CY" +
                "CX" +
                "BX" +
                "CX" +
                "AY" +
                "AX" +
                "AX" +
                "BX" +
                "CX" +
                "BX" +
                "AY" +
                "BX" +
                "BZ" +
                "AY" +
                "AX" +
                "AY" +
                "BX" +
                "BZ" +
                "AX" +
                "AX" +
                "CX" +
                "AX" +
                "AY" +
                "AX" +
                "BX" +
                "AX" +
                "AX" +
                "AZ" +
                "BX" +
                "BY" +
                "CY" +
                "CX" +
                "AY" +
                "AX" +
                "BY" +
                "CX" +
                "AX" +
                "CY" +
                "AX" +
                "AY" +
                "AY" +
                "AX" +
                "AX" +
                "CX" +
                "CX" +
                "AY" +
                "AY" +
                "CX" +
                "AX" +
                "BX" +
                "CX" +
                "BY" +
                "CY" +
                "CX" +
                "BX" +
                "BY" +
                "CX" +
                "BX" +
                "BY" +
                "AX" +
                "AX" +
                "BX" +
                "AY" +
                "AX" +
                "BX" +
                "AX" +
                "CY" +
                "AX" +
                "BX" +
                "AY" +
                "CY" +
                "AX" +
                "AY" +
                "AZ" +
                "CZ" +
                "AX" +
                "AX" +
                "CX" +
                "AX" +
                "BX" +
                "AX" +
                "CX" +
                "CX" +
                "AY" +
                "AX" +
                "CY" +
                "AY" +
                "AX" +
                "BY" +
                "AX" +
                "AY" +
                "AX" +
                "CZ" +
                "CZ" +
                "CX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "CX" +
                "AX" +
                "CX" +
                "BX" +
                "BX" +
                "AX" +
                "AY" +
                "BY" +
                "BX" +
                "BX" +
                "AY" +
                "AY" +
                "AX" +
                "AX" +
                "BY" +
                "BX" +
                "AX" +
                "CX" +
                "BX" +
                "CX" +
                "BY" +
                "BZ" +
                "BY" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "BY" +
                "AX" +
                "CX" +
                "BZ" +
                "AX" +
                "CY" +
                "AX" +
                "BX" +
                "CY" +
                "AX" +
                "AY" +
                "BX" +
                "AX" +
                "BY" +
                "BX" +
                "AY" +
                "CY" +
                "CX" +
                "AY" +
                "AX" +
                "AX" +
                "AX" +
                "CX" +
                "BX" +
                "CX" +
                "AY" +
                "AX" +
                "AY" +
                "CZ" +
                "CX" +
                "AX" +
                "AY" +
                "BX" +
                "BX" +
                "BX" +
                "BX" +
                "AX" +
                "BX" +
                "AZ" +
                "BY" +
                "AX" +
                "AX" +
                "AX" +
                "CZ" +
                "AY" +
                "AY" +
                "CX" +
                "CX" +
                "CY" +
                "BY" +
                "AY" +
                "AX" +
                "AX" +
                "CY" +
                "AX" +
                "CX" +
                "AX" +
                "AX" +
                "CY" +
                "AY" +
                "AX" +
                "CX" +
                "AX" +
                "AY" +
                "CX" +
                "AY" +
                "AX" +
                "AX" +
                "AX" +
                "BX" +
                "BX" +
                "AX" +
                "BY" +
                "CY" +
                "CX" +
                "AY" +
                "BX" +
                "BX" +
                "BZ" +
                "CX" +
                "BY" +
                "AY" +
                "CZ" +
                "BX" +
                "CX" +
                "AX" +
                "AY" +
                "BY" +
                "BX" +
                "CZ" +
                "BX" +
                "AX" +
                "CX" +
                "CX" +
                "AX" +
                "AX" +
                "AY" +
                "BY" +
                "BX" +
                "AY" +
                "CY" +
                "BY" +
                "BY" +
                "AX" +
                "AY" +
                "AX" +
                "BX" +
                "AY" +
                "AX" +
                "AY" +
                "AX" +
                "BZ" +
                "BX" +
                "AX" +
                "AY" +
                "AX" +
                "BY" +
                "AY" +
                "AX" +
                "AX" +
                "CX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "BY" +
                "BX" +
                "AX" +
                "AX" +
                "CY" +
                "CX" +
                "AY" +
                "AX" +
                "BX" +
                "AX" +
                "BX" +
                "BX" +
                "BY" +
                "AX" +
                "BX" +
                "BY" +
                "AX" +
                "BX" +
                "CX" +
                "AX" +
                "AX" +
                "CZ" +
                "AX" +
                "BX" +
                "AX" +
                "BX" +
                "BX" +
                "BY" +
                "AX" +
                "BY" +
                "CY" +
                "AX" +
                "CX" +
                "AX" +
                "BX" +
                "BY" +
                "AX" +
                "CX" +
                "BX" +
                "AX" +
                "CY" +
                "CX" +
                "BX" +
                "AX" +
                "BX" +
                "AZ" +
                "CY" +
                "AX" +
                "AX" +
                "BX" +
                "AY" +
                "BX" +
                "AX" +
                "AY" +
                "BX" +
                "AX" +
                "CY" +
                "AX" +
                "CX" +
                "BX" +
                "AX" +
                "CY" +
                "CX" +
                "AX" +
                "BY" +
                "BX" +
                "AY" +
                "BX" +
                "AX" +
                "BX" +
                "AY" +
                "BX" +
                "AX" +
                "AX" +
                "CX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "CX" +
                "CX" +
                "BX" +
                "BY" +
                "BX" +
                "BZ" +
                "AX" +
                "BX" +
                "BY" +
                "BX" +
                "BX" +
                "AX" +
                "AZ" +
                "AZ" +
                "AX" +
                "BY" +
                "AX" +
                "BX" +
                "BY" +
                "AX" +
                "BY" +
                "BX" +
                "AX" +
                "CX" +
                "CY" +
                "AX" +
                "AX" +
                "BX" +
                "BX" +
                "BY" +
                "AX" +
                "CX" +
                "BY" +
                "AX" +
                "AZ" +
                "AX" +
                "CY" +
                "AY" +
                "BX" +
                "CX" +
                "CX" +
                "AX" +
                "BX" +
                "CX" +
                "AZ" +
                "AX" +
                "AX" +
                "BY" +
                "CX" +
                "AX" +
                "AY" +
                "CZ" +
                "BX" +
                "AY" +
                "AX" +
                "AZ" +
                "CY" +
                "AX" +
                "CX" +
                "AX" +
                "CY" +
                "BX" +
                "AX" +
                "AX" +
                "BY" +
                "AX" +
                "BX" +
                "BX" +
                "BX" +
                "CX" +
                "CX" +
                "AX" +
                "CZ" +
                "AX" +
                "CY" +
                "AX" +
                "CY" +
                "AY" +
                "BY" +
                "BX" +
                "BY" +
                "BX" +
                "CY" +
                "BY" +
                "BY" +
                "BX" +
                "BY" +
                "AY" +
                "AY" +
                "CZ" +
                "AX" +
                "AX" +
                "AX" +
                "AZ" +
                "BX" +
                "BY" +
                "BX" +
                "BY" +
                "AX" +
                "CX" +
                "BX" +
                "AX" +
                "CY" +
                "BX" +
                "CX" +
                "CY" +
                "BY" +
                "AX" +
                "BY" +
                "BX" +
                "CX" +
                "BX" +
                "CX" +
                "BX" +
                "AX" +
                "CX" +
                "BZ" +
                "BZ" +
                "CX" +
                "AY" +
                "BX" +
                "AY" +
                "AX" +
                "BX" +
                "CY" +
                "CX" +
                "AY" +
                "CY" +
                "BZ" +
                "BY" +
                "BY" +
                "BY" +
                "BZ" +
                "BY" +
                "AX" +
                "AX" +
                "AY" +
                "BY" +
                "BY" +
                "AX" +
                "AZ" +
                "CX" +
                "AX" +
                "AY" +
                "CX" +
                "AY" +
                "AX" +
                "BX" +
                "AX" +
                "AX" +
                "CX" +
                "AX" +
                "AX" +
                "CY" +
                "BY" +
                "AY" +
                "AX" +
                "AX" +
                "BY" +
                "AX" +
                "BX" +
                "AX" +
                "AX" +
                "BX" +
                "BX" +
                "AX" +
                "BY" +
                "AX" +
                "AY" +
                "BY" +
                "AY" +
                "AX" +
                "CX" +
                "AY" +
                "AX" +
                "CX" +
                "AX" +
                "AX" +
                "BX" +
                "CY" +
                "CY" +
                "BX" +
                "BZ" +
                "AX" +
                "AY" +
                "AX" +
                "AX" +
                "CZ" +
                "AX" +
                "BX" +
                "AZ" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "CX" +
                "BX" +
                "BX" +
                "CX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "BX" +
                "AX" +
                "CX" +
                "AY" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "BX" +
                "BY" +
                "AY" +
                "AX" +
                "AX" +
                "CX" +
                "CX" +
                "AX" +
                "AX" +
                "CX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "CX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "BX" +
                "AX" +
                "AX" +
                "BY" +
                "CY" +
                "AX" +
                "AY" +
                "CY" +
                "AX" +
                "BX" +
                "BX" +
                "AX" +
                "AX" +
                "AX" +
                "BX" +
                "AX" +
                "AX" +
                "AX" +
                "AY" +
                "AX" +
                "BY" +
                "AY" +
                "AX" +
                "AY" +
                "AX" +
                "CX" +
                "AX" +
                "CY" +
                "BX" +
                "BX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "CY" +
                "AZ" +
                "AX" +
                "BX" +
                "BX" +
                "AX" +
                "AX" +
                "CZ" +
                "AX" +
                "BZ" +
                "BY" +
                "CY" +
                "AX" +
                "AX" +
                "CX" +
                "BX" +
                "BX" +
                "BX" +
                "CX" +
                "AX" +
                "AY" +
                "BY" +
                "CX" +
                "AX" +
                "BY" +
                "AX" +
                "CZ" +
                "BX" +
                "AY" +
                "AX" +
                "AX" +
                "CY" +
                "AX" +
                "AX" +
                "CX" +
                "AX" +
                "BX" +
                "BY" +
                "BY" +
                "BX" +
                "AX" +
                "AY" +
                "CX" +
                "AX" +
                "AX" +
                "AX" +
                "BX" +
                "CX" +
                "BY" +
                "AX" +
                "AX" +
                "AY" +
                "AX" +
                "AX" +
                "BX" +
                "CX" +
                "CX" +
                "AY" +
                "BX" +
                "AX" +
                "AX" +
                "AX" +
                "BY" +
                "AX" +
                "BX" +
                "AX" +
                "AX" +
                "AX" +
                "AY" +
                "AX" +
                "AZ" +
                "CX" +
                "BY" +
                "BX" +
                "AX" +
                "BX" +
                "CX" +
                "AX" +
                "AX" +
                "BX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "BX" +
                "AX" +
                "CX" +
                "AY" +
                "BX" +
                "CX" +
                "AX" +
                "BX" +
                "AX" +
                "BY" +
                "AX" +
                "CY" +
                "AX" +
                "CY" +
                "CX" +
                "BY" +
                "AY" +
                "AX" +
                "AX" +
                "BX" +
                "AX" +
                "CX" +
                "AX" +
                "AZ" +
                "BX" +
                "AX" +
                "AX" +
                "AY" +
                "AX" +
                "AX" +
                "CX" +
                "BY" +
                "CZ" +
                "AX" +
                "AY" +
                "BX" +
                "BX" +
                "AX" +
                "BY" +
                "CX" +
                "AX" +
                "BX" +
                "AY" +
                "BX" +
                "AX" +
                "AY" +
                "AX" +
                "AX" +
                "CY" +
                "BX" +
                "AY" +
                "CX" +
                "CX" +
                "AY" +
                "AY" +
                "AX" +
                "BZ" +
                "AY" +
                "CX" +
                "CX" +
                "CY" +
                "AY" +
                "BX" +
                "BZ" +
                "AX" +
                "BY" +
                "AX" +
                "AX" +
                "BX" +
                "AY" +
                "CX" +
                "CY" +
                "AX" +
                "BY" +
                "AY" +
                "AX" +
                "BZ" +
                "BY" +
                "AX" +
                "BX" +
                "AX" +
                "AX" +
                "BY" +
                "AY" +
                "AX" +
                "AX" +
                "AX" +
                "AY" +
                "AX" +
                "AX" +
                "CX" +
                "AX" +
                "AX" +
                "CX" +
                "AX" +
                "AX" +
                "CZ" +
                "BX" +
                "AY" +
                "AX" +
                "BY" +
                "BX" +
                "AX" +
                "AX" +
                "AX" +
                "CY" +
                "CY" +
                "BY" +
                "AX" +
                "CX" +
                "CX" +
                "BX" +
                "AX" +
                "AX" +
                "AX" +
                "AY" +
                "AX" +
                "AX" +
                "BZ" +
                "CX" +
                "AX" +
                "AX" +
                "AX" +
                "BY" +
                "BX" +
                "CX" +
                "BX" +
                "AX" +
                "BX" +
                "AX" +
                "CX" +
                "AX" +
                "CX" +
                "AX" +
                "CX" +
                "BY" +
                "BX" +
                "AX" +
                "AX" +
                "BY" +
                "BX" +
                "BX" +
                "AX" +
                "BX" +
                "CY" +
                "AX" +
                "AY" +
                "AY" +
                "AY" +
                "AZ" +
                "BY" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "AZ" +
                "AX" +
                "AX" +
                "AX" +
                "BZ" +
                "BY" +
                "CY" +
                "AX" +
                "AX" +
                "BX" +
                "CX" +
                "AY" +
                "AX" +
                "BX" +
                "AX" +
                "AX" +
                "BX" +
                "BY" +
                "AX" +
                "BX" +
                "CX" +
                "BX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "BX" +
                "BX" +
                "CY" +
                "BX" +
                "BX" +
                "AX" +
                "BX" +
                "AX" +
                "BY" +
                "BX" +
                "AX" +
                "AX" +
                "AY" +
                "BX" +
                "AX" +
                "BY" +
                "AY" +
                "BY" +
                "BX" +
                "AZ" +
                "AX" +
                "BY" +
                "AX" +
                "BX" +
                "AX" +
                "AX" +
                "AX" +
                "BY" +
                "BX" +
                "AX" +
                "CZ" +
                "AY" +
                "AY" +
                "CX" +
                "BZ" +
                "BX" +
                "CZ" +
                "BX" +
                "BX" +
                "AX" +
                "AX" +
                "BY" +
                "CX" +
                "AX" +
                "AZ" +
                "BX" +
                "AX" +
                "AX" +
                "BY" +
                "AX" +
                "AX" +
                "AX" +
                "BY" +
                "AX" +
                "CY" +
                "AX" +
                "CY" +
                "AX" +
                "CY" +
                "BX" +
                "AY" +
                "AX" +
                "BX" +
                "AX" +
                "BY" +
                "AX" +
                "BX" +
                "BX" +
                "AZ" +
                "AX" +
                "CY" +
                "BY" +
                "AX" +
                "AX" +
                "CX" +
                "BY" +
                "CY" +
                "CX" +
                "AY" +
                "BY" +
                "AY" +
                "AY" +
                "BX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "AY" +
                "AX" +
                "AX" +
                "AX" +
                "BY" +
                "AX" +
                "AY" +
                "CX" +
                "AX" +
                "BX" +
                "AX" +
                "AX" +
                "AX" +
                "CZ" +
                "AX" +
                "AY" +
                "AX" +
                "CZ" +
                "BY" +
                "BX" +
                "AX" +
                "AZ" +
                "AX" +
                "AX" +
                "AY" +
                "AX" +
                "AX" +
                "AX" +
                "BY" +
                "AX" +
                "BX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "BX" +
                "BZ" +
                "CX" +
                "CX" +
                "CX" +
                "BY" +
                "AX" +
                "BY" +
                "BX" +
                "AY" +
                "BX" +
                "BX" +
                "AX" +
                "CY" +
                "BX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "BY" +
                "CY" +
                "BX" +
                "CY" +
                "BY" +
                "CX" +
                "AY" +
                "CX" +
                "BX" +
                "CX" +
                "BX" +
                "AX" +
                "AX" +
                "BY" +
                "AX" +
                "CX" +
                "AY" +
                "CX" +
                "CX" +
                "BY" +
                "AX" +
                "CX" +
                "CX" +
                "BZ" +
                "AX" +
                "CX" +
                "AY" +
                "BY" +
                "AX" +
                "AY" +
                "AX" +
                "BX" +
                "AX" +
                "AX" +
                "BY" +
                "AZ" +
                "AX" +
                "BY" +
                "BX" +
                "AX" +
                "AY" +
                "BX" +
                "BX" +
                "AX" +
                "AX" +
                "AY" +
                "AX" +
                "CX" +
                "AX" +
                "BX" +
                "CX" +
                "CX" +
                "CY" +
                "AX" +
                "BX" +
                "BY" +
                "AX" +
                "CX" +
                "AX" +
                "BY" +
                "AX" +
                "BX" +
                "BZ" +
                "AX" +
                "AX" +
                "AX" +
                "BX" +
                "CX" +
                "CX" +
                "BX" +
                "AY" +
                "AX" +
                "AY" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "CY" +
                "BX" +
                "AX" +
                "AX" +
                "AX" +
                "BY" +
                "AX" +
                "BX" +
                "BY" +
                "AZ" +
                "AY" +
                "AX" +
                "AY" +
                "AX" +
                "AY" +
                "BZ" +
                "AX" +
                "BY" +
                "BZ" +
                "BX" +
                "AX" +
                "CX" +
                "CY" +
                "AX" +
                "AX" +
                "AX" +
                "BX" +
                "AY" +
                "CX" +
                "AX" +
                "BY" +
                "AY" +
                "BX" +
                "BX" +
                "AX" +
                "AY" +
                "BX" +
                "AY" +
                "CX" +
                "AX" +
                "CX" +
                "AX" +
                "CX" +
                "AX" +
                "AX" +
                "CX" +
                "AX" +
                "AX" +
                "AY" +
                "BX" +
                "CX" +
                "BY" +
                "AY" +
                "AX" +
                "AX" +
                "AX" +
                "AZ" +
                "BY" +
                "AX" +
                "AX" +
                "BY" +
                "AY" +
                "BY" +
                "AX" +
                "BY" +
                "BX" +
                "AX" +
                "AX" +
                "AX" +
                "BX" +
                "BY" +
                "AX" +
                "CZ" +
                "BZ" +
                "AX" +
                "AX" +
                "AX" +
                "BX" +
                "BY" +
                "AX" +
                "BZ" +
                "AX" +
                "AY" +
                "AY" +
                "AY" +
                "CX" +
                "BY" +
                "AX" +
                "AX" +
                "CY" +
                "BX" +
                "AY" +
                "AX" +
                "AX" +
                "BY" +
                "CX" +
                "CX" +
                "CX" +
                "AX" +
                "AX" +
                "AX" +
                "BZ" +
                "AX" +
                "CX" +
                "AX" +
                "AX" +
                "BX" +
                "BX" +
                "AX" +
                "CY" +
                "AX" +
                "BX" +
                "CX" +
                "BY" +
                "AX" +
                "BY" +
                "CX" +
                "AX" +
                "CX" +
                "BY" +
                "AX" +
                "AY" +
                "CX" +
                "CZ" +
                "AX" +
                "CX" +
                "AX" +
                "AX" +
                "CX" +
                "AY" +
                "CX" +
                "BY" +
                "AX" +
                "CZ" +
                "AX" +
                "BX" +
                "BY" +
                "AY" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "AY" +
                "AY" +
                "BX" +
                "CX" +
                "AY" +
                "AX" +
                "CX" +
                "BX" +
                "BY" +
                "CX" +
                "BX" +
                "AX" +
                "BX" +
                "AX" +
                "CY" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "CX" +
                "AX" +
                "BX" +
                "AX" +
                "BX" +
                "AX" +
                "AY" +
                "CX" +
                "CY" +
                "CX" +
                "AZ" +
                "BX" +
                "AZ" +
                "AX" +
                "BY" +
                "AY" +
                "BX" +
                "AX" +
                "BY" +
                "AY" +
                "AX" +
                "BY" +
                "AX" +
                "BX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "BY" +
                "AY" +
                "AX" +
                "AX" +
                "BX" +
                "BZ" +
                "AY" +
                "AY" +
                "CY" +
                "CY" +
                "AX" +
                "CX" +
                "AX" +
                "BY" +
                "BX" +
                "BY" +
                "BX" +
                "CX" +
                "BX" +
                "CX" +
                "AX" +
                "BY" +
                "AX" +
                "BX" +
                "AX" +
                "BX" +
                "CY" +
                "BX" +
                "AX" +
                "AY" +
                "AX" +
                "BY" +
                "CX" +
                "CX" +
                "AX" +
                "BZ" +
                "AX" +
                "AX" +
                "BY" +
                "AX" +
                "AX" +
                "BX" +
                "AY" +
                "CX" +
                "AX" +
                "CY" +
                "AY" +
                "CX" +
                "AY" +
                "AX" +
                "AX" +
                "AX" +
                "AY" +
                "BX" +
                "BX" +
                "AY" +
                "CX" +
                "BY" +
                "AY" +
                "BX" +
                "BX" +
                "BX" +
                "BX" +
                "AX" +
                "BX" +
                "BX" +
                "AX" +
                "CX" +
                "AX" +
                "CX" +
                "CX" +
                "AX" +
                "CX" +
                "BX" +
                "AY" +
                "AZ" +
                "AX" +
                "AX" +
                "AX" +
                "AY" +
                "AX" +
                "AX" +
                "CZ" +
                "AX" +
                "BX" +
                "CX" +
                "AX" +
                "BX" +
                "CX" +
                "CX" +
                "AX" +
                "BY" +
                "AX" +
                "AX" +
                "AX" +
                "AY" +
                "BY" +
                "BY" +
                "AX" +
                "BX" +
                "AX" +
                "CX" +
                "AX" +
                "BY" +
                "CY" +
                "CX" +
                "CX" +
                "BX" +
                "BX" +
                "CX" +
                "AY" +
                "BX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "AY" +
                "BX" +
                "BX" +
                "CY" +
                "CY" +
                "BY" +
                "BX" +
                "AX" +
                "CY" +
                "AX" +
                "CZ" +
                "CX" +
                "AX" +
                "BZ" +
                "AX" +
                "AZ" +
                "CX" +
                "BY" +
                "AX" +
                "AY" +
                "AX" +
                "BX" +
                "AY" +
                "CX" +
                "CY" +
                "BX" +
                "BX" +
                "BY" +
                "BY" +
                "CX" +
                "BY" +
                "BY" +
                "BX" +
                "CX" +
                "CX" +
                "AX" +
                "AX" +
                "AY" +
                "AX" +
                "AY" +
                "BX" +
                "AX" +
                "BY" +
                "BX" +
                "AX" +
                "AX" +
                "AY" +
                "BX" +
                "BX" +
                "AX" +
                "BX" +
                "CY" +
                "AY" +
                "BY" +
                "CY" +
                "BY" +
                "AX" +
                "BY" +
                "BX" +
                "BZ" +
                "AY" +
                "AY" +
                "CY" +
                "BX" +
                "AX" +
                "AX" +
                "BY" +
                "AX" +
                "AX" +
                "BX" +
                "AX" +
                "AX" +
                "AX" +
                "BX" +
                "BX" +
                "BY" +
                "AX" +
                "CX" +
                "AX" +
                "BX" +
                "AX" +
                "AX" +
                "AY" +
                "BX" +
                "BX" +
                "BX" +
                "CX" +
                "BY" +
                "CZ" +
                "AX" +
                "CX" +
                "AX" +
                "BX" +
                "AX" +
                "AY" +
                "BY" +
                "AZ" +
                "AX" +
                "CX" +
                "AY" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "AY" +
                "AX" +
                "CX" +
                "AX" +
                "CY" +
                "BX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "CX" +
                "AX" +
                "BX" +
                "BY" +
                "BY" +
                "BX" +
                "CZ" +
                "CX" +
                "BX" +
                "CY" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "CX" +
                "AX" +
                "BX" +
                "CX" +
                "CX" +
                "AX" +
                "AX" +
                "BX" +
                "AX" +
                "AX" +
                "AX" +
                "BX" +
                "AX" +
                "CX" +
                "AX" +
                "AY" +
                "AX" +
                "BY" +
                "AX" +
                "BX" +
                "AY" +
                "CX" +
                "BX" +
                "CY" +
                "CY" +
                "BX" +
                "AX" +
                "BX" +
                "CX" +
                "AX" +
                "CX" +
                "AX" +
                "CX" +
                "BX" +
                "BX" +
                "CX" +
                "CX" +
                "BX" +
                "BX" +
                "CY" +
                "BX" +
                "AX" +
                "BX" +
                "BX" +
                "BY" +
                "AY" +
                "BX" +
                "AX" +
                "CY" +
                "AY" +
                "CY" +
                "AX" +
                "BY" +
                "AX" +
                "AX" +
                "AX" +
                "BY" +
                "BX" +
                "AY" +
                "AX" +
                "AX" +
                "AY" +
                "BX" +
                "BY" +
                "AY" +
                "BX" +
                "CX" +
                "CZ" +
                "BX" +
                "AY" +
                "AX" +
                "CX" +
                "AX" +
                "CX" +
                "BZ" +
                "CX" +
                "AY" +
                "AX" +
                "CX" +
                "BY" +
                "AZ" +
                "BY" +
                "AX" +
                "AX" +
                "AY" +
                "CX" +
                "AZ" +
                "AX" +
                "BY" +
                "AX" +
                "BX" +
                "AY" +
                "AY" +
                "AX" +
                "AX" +
                "AX" +
                "CY" +
                "BX" +
                "AX" +
                "BX" +
                "BY" +
                "BY" +
                "AX" +
                "AX" +
                "AY" +
                "AX" +
                "CX" +
                "BX" +
                "CX" +
                "BX" +
                "BX" +
                "CY" +
                "AY" +
                "BX" +
                "AX" +
                "AX" +
                "AX" +
                "CX" +
                "CX" +
                "AX" +
                "BX" +
                "AX" +
                "AX" +
                "AZ" +
                "AX" +
                "CX" +
                "BX" +
                "AX" +
                "CY" +
                "AY" +
                "CY" +
                "BY" +
                "BY" +
                "BZ" +
                "AX" +
                "CX" +
                "AX" +
                "BY" +
                "BY" +
                "AX" +
                "BY" +
                "AX" +
                "BY" +
                "BX" +
                "BX" +
                "CX" +
                "BY" +
                "BX" +
                "AX" +
                "AY" +
                "BX" +
                "AX" +
                "BZ" +
                "AY" +
                "BX" +
                "BX" +
                "AY" +
                "CY" +
                "BX" +
                "BY" +
                "AX" +
                "BX" +
                "AY" +
                "AY" +
                "BX" +
                "BY" +
                "BX" +
                "AX" +
                "CX" +
                "AX" +
                "AX" +
                "AX" +
                "BY" +
                "AY" +
                "BX" +
                "CX" +
                "CZ" +
                "AX" +
                "BY" +
                "AY" +
                "AX" +
                "BX" +
                "AX" +
                "AY" +
                "AX" +
                "AY" +
                "AX" +
                "AX" +
                "AX" +
                "CX" +
                "AY" +
                "CY" +
                "AX" +
                "AX" +
                "CZ" +
                "BX" +
                "AY" +
                "BX" +
                "BX" +
                "BX" +
                "BX" +
                "BX" +
                "AX" +
                "AX" +
                "BX" +
                "BY" +
                "AX" +
                "CY" +
                "CX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "AY" +
                "BY" +
                "AX" +
                "AX" +
                "AZ" +
                "CY" +
                "CY" +
                "BX" +
                "CZ" +
                "AX" +
                "AX" +
                "AX" +
                "BZ" +
                "BY" +
                "AX" +
                "AX" +
                "AX" +
                "BX" +
                "AX" +
                "CX" +
                "CX" +
                "CX" +
                "BX" +
                "AX" +
                "AX" +
                "CZ" +
                "BZ" +
                "CY" +
                "AX" +
                "AX" +
                "AX" +
                "CZ" +
                "AX" +
                "AX" +
                "CX" +
                "CX" +
                "AX" +
                "CY" +
                "AX" +
                "AY" +
                "AX" +
                "AX" +
                "AZ" +
                "CX" +
                "CX" +
                "AY" +
                "BX" +
                "BX" +
                "AY" +
                "AX" +
                "BX" +
                "CY" +
                "AX" +
                "AY" +
                "BZ" +
                "AX" +
                "CY" +
                "AX" +
                "BY" +
                "AX" +
                "AY" +
                "AX" +
                "CZ" +
                "AX" +
                "BX" +
                "AX" +
                "BY" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "BY" +
                "CX" +
                "AX" +
                "BX" +
                "AX" +
                "AY" +
                "AZ" +
                "AX" +
                "AX" +
                "BY" +
                "BX" +
                "CX" +
                "AX" +
                "AX" +
                "BX" +
                "BY" +
                "BY" +
                "AY" +
                "BZ" +
                "BY" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "BX" +
                "CY" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "AX" +
                "BY" +
                "AX" +
                "BX" +
                "CX" +
                "CX" +
                "CX" +
                "CX" +
                "AX" +
                "BY" +
                "AX" +
                "BX" +
                "BX" +
                "AX" +
                "AX" +
                "CZ" +
                "AX" +
                "BX" +
                "BX" +
                "CX" +
                "AX" +
                "BX" +
                "BX" +
                "BX" +
                "BX" +
                "BY" +
                "AX" +
                "BX" +
                "AY" +
                "AX" +
                "AY" +
                "BY" +
                "AX" +
                "CY" +
                "BX" +
                "AX" +
                "AX" +
                "AX" +
                "AZ" +
                "AY" +
                "AX" +
                "CX" +
                "CX" +
                "BX" +
                "AX" +
                "AX" +
                "BX" +
                "AX" +
                "AY" +
                "CZ" +
                "AY" +
                "BX" +
                "BY" +
                "AX" +
                "CY" +
                "BZ";
    }
}
