package user.jacobandrudy.projects;
public class RPS {
    public static void main(String args[]){
        createInput(input());
    }

    public static void createInput(String input) {
        System.out.println(input.charAt(5));

        
    }
    
























    public static String input() {
        return "A Z\n" + //
                "A Y\n" + //
                "B X\n" + //
                "B X\n" + //
                "C X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "A Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "C X\n" + //
                "B X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "C Z\n" + //
                "C X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "C X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "C X\n" + //
                "B X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A Y\n" + //
                "C X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "C X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A Z\n" + //
                "B X\n" + //
                "C X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "C X\n" + //
                "A X\n" + //
                "A Z\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "B X\n" + //
                "A Y\n" + //
                "B Z\n" + //
                "B X\n" + //
                "C Y\n" + //
                "B X\n" + //
                "B Z\n" + //
                "A Y\n" + //
                "B X\n" + //
                "C X\n" + //
                "C Y\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C Z\n" + //
                "A X\n" + //
                "C X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "B Z\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Z\n" + //
                "C X\n" + //
                "A Z\n" + //
                "C Z\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "C X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "C X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "C X\n" + //
                "B Z\n" + //
                "B X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "C X\n" + //
                "C X\n" + //
                "B X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "B X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "C X\n" + //
                "B X\n" + //
                "C X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "C X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Z\n" + //
                "C X\n" + //
                "B X\n" + //
                "C X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A Z\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "B X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C Y\n" + //
                "C X\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "C X\n" + //
                "C Y\n" + //
                "A Y\n" + //
                "A Z\n" + //
                "B X\n" + //
                "C X\n" + //
                "B X\n" + //
                "C X\n" + //
                "A X\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "B X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "A Y\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "B X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "A X\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "A Y\n" + //
                "C X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "C Y\n" + //
                "A Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "C X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "C Y\n" + //
                "A Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "B X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "A Y\n" + //
                "A Y\n" + //
                "B X\n" + //
                "C Y\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "B X\n" + //
                "C Z\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Z\n" + //
                "C X\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "B X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B X\n" + //
                "B X\n" + //
                "A Y\n" + //
                "C X\n" + //
                "B X\n" + //
                "A Z\n" + //
                "A X\n" + //
                "A Z\n" + //
                "C X\n" + //
                "A X\n" + //
                "C Z\n" + //
                "C X\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "B X\n" + //
                "A X\n" + //
                "C Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "C X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "C X\n" + //
                "B X\n" + //
                "B X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B X\n" + //
                "B X\n" + //
                "A X\n" + //
                "B X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "C Y\n" + //
                "A X\n" + //
                "A Y\n" + //
                "C Z\n" + //
                "A Y\n" + //
                "C X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A Z\n" + //
                "A Y\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A Z\n" + //
                "C X\n" + //
                "C Z\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "C Z\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Z\n" + //
                "A X\n" + //
                "C X\n" + //
                "A Y\n" + //
                "C X\n" + //
                "A Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "B X\n" + //
                "B Z\n" + //
                "B X\n" + //
                "B X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A Y\n" + //
                "C X\n" + //
                "A Z\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Z\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C Z\n" + //
                "A Y\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "C X\n" + //
                "C Y\n" + //
                "C X\n" + //
                "B X\n" + //
                "C X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "C X\n" + //
                "B X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "B Z\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "B Z\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Z\n" + //
                "B X\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "C X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "C X\n" + //
                "A Y\n" + //
                "A Y\n" + //
                "C X\n" + //
                "A X\n" + //
                "B X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "C X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "A Y\n" + //
                "C Y\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A Z\n" + //
                "C Z\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "C X\n" + //
                "C X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "C Z\n" + //
                "C Z\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "C X\n" + //
                "B X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "B X\n" + //
                "B X\n" + //
                "A Y\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "C X\n" + //
                "B X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "B Z\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "C Y\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "A Y\n" + //
                "C Y\n" + //
                "C X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "B X\n" + //
                "C X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A Y\n" + //
                "C Z\n" + //
                "C X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "B X\n" + //
                "B X\n" + //
                "B X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Z\n" + //
                "A Y\n" + //
                "A Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "C X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "B X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "C X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "B X\n" + //
                "B Z\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "C Z\n" + //
                "B X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "B X\n" + //
                "C Z\n" + //
                "B X\n" + //
                "A X\n" + //
                "C X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "B X\n" + //
                "A Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B Z\n" + //
                "B X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "C X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "B X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Z\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "B X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "B X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "C X\n" + //
                "B X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "B X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "C X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "C X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "B Z\n" + //
                "A X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "C X\n" + //
                "C Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A Z\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A Y\n" + //
                "B X\n" + //
                "C X\n" + //
                "C X\n" + //
                "A X\n" + //
                "B X\n" + //
                "C X\n" + //
                "A Z\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "C Z\n" + //
                "B X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "B X\n" + //
                "B X\n" + //
                "C X\n" + //
                "C X\n" + //
                "A X\n" + //
                "C Z\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "B X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "A Y\n" + //
                "C Z\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Z\n" + //
                "B X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "B X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "B X\n" + //
                "C X\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "C X\n" + //
                "B X\n" + //
                "C X\n" + //
                "B X\n" + //
                "A X\n" + //
                "C X\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "C X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "C Y\n" + //
                "C X\n" + //
                "A Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A Z\n" + //
                "C X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "C X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "B X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B X\n" + //
                "B Z\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Z\n" + //
                "A X\n" + //
                "B X\n" + //
                "A Z\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "B X\n" + //
                "B X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "A X\n" + //
                "A Y\n" + //
                "C Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "B X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "A X\n" + //
                "B X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Z\n" + //
                "A X\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "B X\n" + //
                "B X\n" + //
                "B X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C Z\n" + //
                "B X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "C X\n" + //
                "C X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A Z\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "B X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "C X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A X\n" + //
                "C Y\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A Z\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "C Z\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "B X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "B X\n" + //
                "A Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "A Y\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B Z\n" + //
                "A Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "C Y\n" + //
                "A Y\n" + //
                "B X\n" + //
                "B Z\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A Y\n" + //
                "C X\n" + //
                "C Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Z\n" + //
                "B X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "C X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Z\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "C X\n" + //
                "B X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "B X\n" + //
                "A X\n" + //
                "B X\n" + //
                "C Y\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A Y\n" + //
                "A Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Z\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "C X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "C X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "B X\n" + //
                "C Y\n" + //
                "B X\n" + //
                "B X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "B X\n" + //
                "A Z\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "C Z\n" + //
                "A Y\n" + //
                "A Y\n" + //
                "C X\n" + //
                "B Z\n" + //
                "B X\n" + //
                "C Z\n" + //
                "B X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A X\n" + //
                "A Z\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A X\n" + //
                "C Y\n" + //
                "B X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "B X\n" + //
                "A Z\n" + //
                "A X\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "C X\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "A Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A Y\n" + //
                "C X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Z\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "C Z\n" + //
                "B Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "A Z\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "B Z\n" + //
                "C X\n" + //
                "C X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "B X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B X\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A Y\n" + //
                "C X\n" + //
                "B X\n" + //
                "C X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "A Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "C X\n" + //
                "B Z\n" + //
                "A X\n" + //
                "C X\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "B X\n" + //
                "C X\n" + //
                "C X\n" + //
                "C Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "B Z\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "C X\n" + //
                "C X\n" + //
                "B X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B Z\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "B X\n" + //
                "A X\n" + //
                "C X\n" + //
                "C Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A Y\n" + //
                "C X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "B X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "A Y\n" + //
                "C X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C Z\n" + //
                "B Z\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Z\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A Y\n" + //
                "A Y\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "B X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Z\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "B X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A Y\n" + //
                "C X\n" + //
                "C Z\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A Y\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C Z\n" + //
                "A X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A Y\n" + //
                "B X\n" + //
                "C X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "C X\n" + //
                "C Y\n" + //
                "C X\n" + //
                "A Z\n" + //
                "B X\n" + //
                "A Z\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "B Z\n" + //
                "A Y\n" + //
                "A Y\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "C X\n" + //
                "B X\n" + //
                "C X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "B X\n" + //
                "C Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "A X\n" + //
                "B Z\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A Y\n" + //
                "C X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A Y\n" + //
                "C X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "B X\n" + //
                "A Y\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "B X\n" + //
                "B X\n" + //
                "B X\n" + //
                "B X\n" + //
                "A X\n" + //
                "B X\n" + //
                "B X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "C X\n" + //
                "C X\n" + //
                "A X\n" + //
                "C X\n" + //
                "B X\n" + //
                "A Y\n" + //
                "A Z\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Z\n" + //
                "A X\n" + //
                "B X\n" + //
                "C X\n" + //
                "A X\n" + //
                "B X\n" + //
                "C X\n" + //
                "C X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "B X\n" + //
                "B X\n" + //
                "C X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "B X\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A X\n" + //
                "C Z\n" + //
                "C X\n" + //
                "A X\n" + //
                "B Z\n" + //
                "A X\n" + //
                "A Z\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "A Y\n" + //
                "C X\n" + //
                "C Y\n" + //
                "B X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B X\n" + //
                "C X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "B X\n" + //
                "A X\n" + //
                "B X\n" + //
                "C Y\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "B Z\n" + //
                "A Y\n" + //
                "A Y\n" + //
                "C Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "B X\n" + //
                "B X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "C Z\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "A X\n" + //
                "C X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B X\n" + //
                "C Z\n" + //
                "C X\n" + //
                "B X\n" + //
                "C Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "B X\n" + //
                "C X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "A Y\n" + //
                "C X\n" + //
                "B X\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "B X\n" + //
                "C X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "C X\n" + //
                "B X\n" + //
                "B X\n" + //
                "C X\n" + //
                "C X\n" + //
                "B X\n" + //
                "B X\n" + //
                "C Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "B X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A Y\n" + //
                "C Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "B X\n" + //
                "C X\n" + //
                "C Z\n" + //
                "B X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "C X\n" + //
                "B Z\n" + //
                "C X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "C X\n" + //
                "A Z\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "A Y\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "B X\n" + //
                "C X\n" + //
                "B X\n" + //
                "B X\n" + //
                "C Y\n" + //
                "A Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "C X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Z\n" + //
                "A X\n" + //
                "C X\n" + //
                "B X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "B X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "B Z\n" + //
                "A Y\n" + //
                "B X\n" + //
                "B X\n" + //
                "A Y\n" + //
                "C Y\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "A Y\n" + //
                "A Y\n" + //
                "B X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "B X\n" + //
                "C X\n" + //
                "C Z\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A Y\n" + //
                "C Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Z\n" + //
                "B X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "B X\n" + //
                "B X\n" + //
                "B X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C Y\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B X\n" + //
                "C Z\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "C X\n" + //
                "C X\n" + //
                "C X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Z\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Z\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "C X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Z\n" + //
                "C X\n" + //
                "C X\n" + //
                "A Y\n" + //
                "B X\n" + //
                "B X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "C Y\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B Z\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "C Z\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A Z\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "C Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "C X\n" + //
                "C X\n" + //
                "C X\n" + //
                "C X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Z\n" + //
                "A X\n" + //
                "B X\n" + //
                "B X\n" + //
                "C X\n" + //
                "A X\n" + //
                "B X\n" + //
                "B X\n" + //
                "B X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Z\n" + //
                "A Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "C X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "C Z\n" + //
                "A Y\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C Y\n" + //
                "B Z";
    }
}
